---
- name: get timestamp from localhost
  hosts: localhost
  gather_facts: true

- name: bigip backups
  hosts: bigip
  connection: local

  pre_tasks:
    - name: ensure the destination directory exists
      file:
        path: "{{ basedir }}/{{ inventory_hostname }}"
        state: directory

  tasks:
    - name: create and download ucs file
      bigip_ucs_fetch:
        src: backup.ucs
        dest: >-
          {{ basedir }}/{{ inventory_hostname }}/{{ inventory_hostname }}_{{
          hostvars['localhost'].ansible_date_time.date }}.ucs
        provider:
          server: "{{ inventory_hostname }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          validate_certs: false

  post_tasks:
    - name: delete ucs file
      bigip_ucs:
        ucs: backup.ucs
        state: absent
        provider:
          server: "{{ inventory_hostname }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          validate_certs: false

    - name: delete files that are older than the retention period
      shell: "find {{ basedir }}/{{ inventory_hostname }} -type f -mtime +{{ retention_time }} -exec rm {} \\;"
