---
- name: get timestamp from localhost
  hosts: localhost
  gather_facts: true

- name: checkpoint backups
  hosts: checkpoint
  connection: local

  pre_tasks:
    - name: ensure the destination directory exists
      file:
        path: "{{ basedir }}/{{ inventory_hostname }}"
        state: directory

  tasks:
    - name: copy remote backup to local server
      shell: >-
        scp {{ ansible_user }}@{{ inventory_hostname }}:/var/log/CPbackup/backups/*$(date +%d_%b_%Y)*.tgz {{ 
        basedir }}/{{ inventory_hostname }}/{{ inventory_hostname }}_{{
        hostvars['localhost'].ansible_date_time.date }}.tgz

  post_tasks:
    - name: delete files that are older than the retention period
      shell: "find {{ basedir }}/{{ inventory_hostname }} -type f -mtime +{{ retention_time }} -exec rm {} \\;"